### ISSUE TITLE
Colab error on import SingingVoiceTranscription

### ISSUE THREAD

**Issue by nicolalandro** [B05901022/VOCANO#3]
Running the colab notebook I reach the following error error on `from vocano.core import SingingVoiceTranscription`:
```
ValueError: cupy_backends.cuda.api.runtime.PointerAttributes size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
```

Full log:
```
/usr/local/lib/python3.7/dist-packages/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-8-16881491b4a4>](https://localhost:8080/#) in <module>()
      3 import argparse
      4 from pathlib import Path
----> 5 from vocano.core import SingingVoiceTranscription
      6 
      7 file_name = input('Output file name:')

9 frames

[/usr/local/lib/python3.7/dist-packages/cupy/linalg/decomposition.py](https://localhost:8080/#) in <module>()
      5 from cupy_backends.cuda.libs import cusolver
      6 from cupy.cuda import device
----> 7 from cupy.cusolver import check_availability
      8 from cupy.linalg import util
      9 

cupy/cusolver.pyx in init cupy.cusolver()

ValueError: cupy_backends.cuda.api.runtime.PointerAttributes size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
```

**Comment by B05901022** [comment]
Hi,
It seems that cupy and pytorch no longer support cuda 10.1 which causes the problem. Sorry that I do not have the resource to refactor the code to match the latest versions and/or retrain models based on the new pytorch version. For debugging, maybe try to replace the `Download other prerequisites` section with the code below. 
```shell
#@title Download other prerequisites

!pip install apex
!pip install certifi
!pip install chardet
!pip install cupy-cuda101
!pip install fastrlock
!pip install future
!pip install googledrivedownloader
!pip install idna
!pip install mido
!pip install numpy
!pip install pillow
!pip install pretty-midi
!pip install requests
!pip install scipy
!pip install six
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install tqdm
!pip install urllib3
```
For retraining to fit newer pytorch versions, please refer to [our training code][our training code]. For inference only usages, please refer to [Omnizart][Omnizart] for a better sustained code, which also includes other functionalities useful for music transcription. Hope the information can help you.

[our training code]: https://github.com/B05901022/Note-Segmentation-SSL
[Omnizart]: https://github.com/Music-and-Culture-Technology-Lab/omnizart

**Comment by nicolalandro** [comment]
Thank you, I try but with no good results and also from Omnizart I cannot transcribe polyphonic singing voice I think or it it my mistake?

**Comment by B05901022** [comment]
Hi,
Thank you for trying our work. However, our work is focusing on transcribing monophonic singing voice from polyphonic music (due to the restriction of the training dataset), thus direct transcribing polyphonic singing voice might be challenging and might result in bad performance. Additionally, if the separation model does not perform well, the results might be bad too.

**Comment by MohammedMehdiTBER** [comment]
> Hi, Thank you for trying our work. However, our work is focusing on transcribing monophonic singing voice from polyphonic music (due to the restriction of the training dataset), thus direct transcribing polyphonic singing voice might be challenging and might result in bad performance. Additionally, if the separation model does not perform well, the results might be bad too.

Omnizart is also unmaintained.

**Comment by B05901022** [comment]
Hi,
Thank you for trying our work., but unfortunately I am no longer working at Music and Culture Technology Lab now, thus I cannot provide direct support for issues from Omnizart. If you have more issues on Omnizart, please leave a Github issue on the Omnizart repository or contact [the main contributor](https://github.com/BreezeWhite) of Omnizart.
