### ISSUE TITLE
Cannot download the pretrained weights of the two models

### ISSUE THREAD

**Issue by shansongliu** [B05901022/VOCANO#6]
Dear authors, I cannot download the pretrained weights for both "PyramidNet_ShakeDrop" and "Patch_CNN" models, would you please kindly send me the files? My email address is dadinghh2 [at] gmail [dot] com

**Comment by B05901022** [comment]
Hi,

The pretrained weights can be accessed [here](https://drive.google.com/drive/folders/1DwAw0k9BJPJ02jcuHnevvy_QoqFrtDIp?usp=share_link).

**Comment by shansongliu** [comment]
> Hi,
> 
> The pretrained weights can be accessed [here](https://drive.google.com/drive/folders/1DwAw0k9BJPJ02jcuHnevvy_QoqFrtDIp?usp=share_link).

Many thanks for your quick reply!!!
